# Generated by Django 5.2.1 on 2025-05-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_linkr_app', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], max_length=50, unique=True),
        ),
    ]
