# Generated by Django 5.2.1 on 2025-05-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_linkr_app', '0004_fix_user_table_references'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionlog',
            options={'ordering': ['-login_time']},
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['user', 'session_id', 'is_expired'], name='health_link_user_id_beda60_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['login_time', 'logout_time'], name='health_link_login_t_a8131f_idx'),
        ),
    ]
