# Generated by Django 5.2.1 on 2025-05-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_linkr_app', '0005_update_session_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-datetime']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancellation_reason',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'datetime'], name='health_link_status_f05797_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='health_link_patient_eb8824_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status'], name='health_link_doctor__1de100_idx'),
        ),
    ]
