# Generated by Django 5.2.1 on 2025-05-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_linkr_app', '0007_update_doctor_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='facilities',
            field=models.JSONField(default=list, help_text='List of available facilities and equipment'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='insurance_accepted',
            field=models.JSONField(default=list, help_text='List of accepted insurance providers'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='specialties',
            field=models.JSONField(default=list, help_text='Medical specialties available at this clinic'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='opening_hours',
            field=models.JSONField(default=dict, help_text='Format: {"monday": {"open": "09:00", "close": "17:00"}, ...}'),
        ),
    ]
